enum CurrencyIso {
  Kuwait_KWD,
  SaudiArabia_SAR,
  Bahrain_BHD,
  UAE_AED,
  Qatar_QAR,
  Oman_MOR,
  Jordan_JOD,
  UnitedStates_USD,
  Euro_EUR,
  Cuban_Convertible_Peso_CUC,
  Falkland_Islands_Pound_FKP,
  Indonesian_Rupiah_IDR,
  Brazilian_Real_BRL,
  Costa_Rican_Colon_CRC,
  Maldivian_Rufiyaa_MVR,
  Brunei_Dollar_BND,
  Romanian_Leu_RON,
  Yemeni_Rial_YER,
  Lesotho_Loti_LSL,
  Mongolian_Tugrik_MNT,
  Papua_New_Guinean_Kina_PGK,
  Liberian_Dollar_LRD,
  Venezuelan_Bolivar_Soberano_VES,
  Cape_Verdean_Escudo_CVE,
  Palladium_Ounce_XPD,
  Haitian_Gourde_HTG,
  Saint_Helena_Pound_SHP,
  Kenyan_Shilling_KES,
  Moldovan_Leu_MDL,
  Kyrgystani_Som_KGS,
  New_Zealand_Dollar_NZD,
  Jersey_Pound_JEP,
  Macanese_Pataca_MOP,
  Moroccan_Dirham_MAD,
  Ethiopian_Birr_ETB,
  Turkish_Lira_TRY,
  Zambian_Kwacha_ZMW,
  East_Caribbean_Dollar_XCD,
  Libyan_Dinar_LYD,
  Sudanese_Pound_SDG,
  Tanzanian_Shilling_TZS,
  Vanuatu_Vatu_VUV,
  Platinum_Ounce_XPT,
  Fijian_Dollar_FJD,
  SaoTomAndPrincipeDobraSTD,
  Polish_Zloty_PLN,
  Canadian_Dollar_CAD,
  Guernsey_Pound_GGP,
  Chilean_Unit_of_Account_UF_CLF,
  Eritrean_Nakfa_ERN,
  Somali_Shilling_SOS,
  Botswanan_Pula_BWP,
  Belize_Dollar_BZD,
  Salvadoran_Colon_SVC,
  Sao_Tome_and_Principe_Dobra_STN,
  Azerbaijani_Manat_AZN,
  Barbadian_Dollar_BBD,
  Mauritian_Rupee_MUR,
  Special_Drawing_Rights_XDR,
  Laotian_Kip_LAK,
  Swazi_Lilangeni_SZL,
  Czech_Republic_Koruna_CZK,
  Mexican_Peso_MXN,
  CFP_Franc_XPF,
  Jamaican_Dollar_JMD,
  Burundian_Franc_BIF,
  Gibraltar_Pound_GIP,
  Namibian_Dollar_NAD,
  Syrian_Pound_SYP,
  Surinamese_Dollar_SRD,
  CFA_Franc_BEAC_XAF,
  North_Korean_Won_KPW,
  Norwegian_Krone_NOK,
  Singapore_Dollar_SGD,
  Bhutanese_Ngultrum_BTN,
  Chinese_Yuan_CNY,
  Malaysian_Ringgit_MYR,
  Afghan_Afghani_AFN,
  BosniaHerzegovinaConvertibleMarkBAM,
  Danish_Krone_DKK,
  South_Korean_Won_KRW,
  Chilean_Peso_CLP,
  Guatemalan_Quetzal_GTQ,
  Serbian_Dinar_RSD,
  Turkmenistani_Manat_TMT,
  Armenian_Dram_AMD,
  MauritanianOuguiyaMRO,
  Solomon_Islands_Dollar_SBD,
  Belarusian_Ruble_BYN,
  Bangladeshi_Taka_BDT,
  Malawian_Kwacha_MWK,
  Pakistani_Rupee_PKR,
  South_African_Rand_ZAR,
  Zimbabwean_Dollar_ZWL,
  Bolivian_Boliviano_BOB,
  Gold_Ounce_XAU,
  Trinidad_and_Tobago_Dollar_TTD,
  Peruvian_Nuevo_Sol_PEN,
  Australian_Dollar_AUD,
  Sri_Lankan_Rupee_LKR,
  Sierra_Leonean_Leone_SLL,
  Israeli_New_Sheqel_ILS,
  Bitcoin_BTC,
  Lebanese_Pound_LBP,
  Rwandan_Franc_RWF,
  Croatian_Kuna_HRK,
  Honduran_Lempira_HNL,
  Bermudan_Dollar_BMD,
  Venezuelan_Bolivar_Fuerte_Old_VEF,
  Congolese_Franc_CDF,
  Guinean_Franc_GNF,
  Indian_Rupee_INR,
  British_Pound_Sterling_GBP,
  Samoan_Tala_WST,
  Netherlands_Antillean_Guilder_ANG,
  Manx_pound_IMP,
  Nicaraguan_Cordoba_NIO,
  Algerian_Dinar_DZD,
  South_Sudanese_Pound_SSP,
  Swiss_Franc_CHF,
  Bulgarian_Lev_BGN,
  Egyptian_Pound_EGP,
  Cayman_Islands_Dollar_KYD,
  Mauritanian_Ouguiya_MRU,
  Japanese_Yen_JPY,
  Philippine_Peso_PHP,
  Paraguayan_Guarani_PYG,
  Swedish_Krona_SEK,
  Cuban_Peso_CUP,
  Hong_Kong_Dollar_HKD,
  Iraqi_Dinar_IQD,
  Dominican_Peso_DOP,
  Kazakhstani_Tenge_KZT,
  Hungarian_Forint_HUF,
  Nigerian_Naira_NGN,
  New_Taiwan_Dollar_TWD,
  Nepalese_Rupee_NPR,
  Ugandan_Shilling_UGX,
  Silver_Ounce_XAG,
  Angolan_Kwanza_AOA,
  Comorian_Franc_KMF,
  Myanma_Kyat_MMK,
  CFA_Franc_BCEAO_XOF,
  Georgian_Lari_GEL,
  Gambian_Dalasi_GMD,
  Seychellois_Rupee_SCR,
  Tunisian_Dinar_TND,
  Cambodian_Riel_KHR,
  Chinese_Yuan_Offshore_CNH,
  Argentine_Peso_ARS,
  Tajikistani_Somoni_TJS,
  Russian_Ruble_RUB,
  Ghanaian_Cedi_GHS,
  Guyanaese_Dollar_GYD,
  Djiboutian_Franc_DJF,
  Mozambican_Metical_MZN,
  Ukrainian_Hryvnia_UAH,
  Bahamian_Dollar_BSD,
  Aruban_Florin_AWG,
  Vietnamese_Dong_VND,
  Icelandic_Krna_ISK,
  Uzbekistan_Som_UZS,
  Thai_Baht_THB,
  Uruguayan_Peso_UYU,
  Macedonian_Denar_MKD,
  Malagasy_Ariary_MGA,
  Colombian_Peso_COP,
  Panamanian_Balboa_PAB,
  Iranian_Rial_IRR,
  TonganPangaTOP,
  Albanian_Lek_ALL
}

Map<CurrencyIso, String> currencies = {
  CurrencyIso.Kuwait_KWD: "KWD",
  CurrencyIso.SaudiArabia_SAR: "SAR",
  CurrencyIso.Bahrain_BHD: "BHD",
  CurrencyIso.UAE_AED: "AED",
  CurrencyIso.Qatar_QAR: "QAR",
  CurrencyIso.Oman_MOR: "MOR",
  CurrencyIso.Jordan_JOD: "JOD",
  CurrencyIso.UnitedStates_USD: "USD",
  CurrencyIso.Euro_EUR: "EUR",
  CurrencyIso.Cuban_Convertible_Peso_CUC: "CUC",
  CurrencyIso.Falkland_Islands_Pound_FKP: "FKP",
  CurrencyIso.Indonesian_Rupiah_IDR: "IDR",
  CurrencyIso.Brazilian_Real_BRL: "BRL",
  CurrencyIso.Costa_Rican_Colon_CRC: "CRC",
  CurrencyIso.Maldivian_Rufiyaa_MVR: "MVR",
  CurrencyIso.Brunei_Dollar_BND: "BND",
  CurrencyIso.Romanian_Leu_RON: "RON",
  CurrencyIso.Yemeni_Rial_YER: "YER",
  CurrencyIso.Lesotho_Loti_LSL: "LSL",
  CurrencyIso.Mongolian_Tugrik_MNT: "MNT",
  CurrencyIso.Papua_New_Guinean_Kina_PGK: "PGK",
  CurrencyIso.Liberian_Dollar_LRD: "LRD",
  CurrencyIso.Venezuelan_Bolivar_Soberano_VES: "VES",
  CurrencyIso.Cape_Verdean_Escudo_CVE: "CVE",
  CurrencyIso.Palladium_Ounce_XPD: "XPD",
  CurrencyIso.Haitian_Gourde_HTG: "HTG",
  CurrencyIso.Saint_Helena_Pound_SHP: "SHP",
  CurrencyIso.Kenyan_Shilling_KES: "KES",
  CurrencyIso.Moldovan_Leu_MDL: "MDL",
  CurrencyIso.Kyrgystani_Som_KGS: "KGS",
  CurrencyIso.New_Zealand_Dollar_NZD: "NZD",
  CurrencyIso.Jersey_Pound_JEP: "JEP",
  CurrencyIso.Macanese_Pataca_MOP: "MOP",
  CurrencyIso.Moroccan_Dirham_MAD: "MAD",
  CurrencyIso.Ethiopian_Birr_ETB: "ETB",
  CurrencyIso.Turkish_Lira_TRY: "TRY",
  CurrencyIso.Zambian_Kwacha_ZMW: "ZMW",
  CurrencyIso.East_Caribbean_Dollar_XCD: "XCD",
  CurrencyIso.Libyan_Dinar_LYD: "LYD",
  CurrencyIso.Sudanese_Pound_SDG: "SDG",
  CurrencyIso.Tanzanian_Shilling_TZS: "TZS",
  CurrencyIso.Vanuatu_Vatu_VUV: "VUV",
  CurrencyIso.Platinum_Ounce_XPT: "XPT",
  CurrencyIso.Fijian_Dollar_FJD: "FJD",
  CurrencyIso.SaoTomAndPrincipeDobraSTD: "SaoTomAndPrincipeDobraSTD",
  CurrencyIso.Polish_Zloty_PLN: "PLN",
  CurrencyIso.Canadian_Dollar_CAD: "CAD",
  CurrencyIso.Guernsey_Pound_GGP: "GGP",
  CurrencyIso.Chilean_Unit_of_Account_UF_CLF: "CLF",
  CurrencyIso.Eritrean_Nakfa_ERN: "ERN",
  CurrencyIso.Somali_Shilling_SOS: "SOS",
  CurrencyIso.Botswanan_Pula_BWP: "BWP",
  CurrencyIso.Belize_Dollar_BZD: "BZD",
  CurrencyIso.Salvadoran_Colon_SVC: "SVC",
  CurrencyIso.Sao_Tome_and_Principe_Dobra_STN: "STN",
  CurrencyIso.Azerbaijani_Manat_AZN: "AZN",
  CurrencyIso.Barbadian_Dollar_BBD: "BBD",
  CurrencyIso.Mauritian_Rupee_MUR: "MUR",
  CurrencyIso.Special_Drawing_Rights_XDR: "XDR",
  CurrencyIso.Laotian_Kip_LAK: "LAK",
  CurrencyIso.Swazi_Lilangeni_SZL: "SZL",
  CurrencyIso.Czech_Republic_Koruna_CZK: "CZK",
  CurrencyIso.Mexican_Peso_MXN: "MXN",
  CurrencyIso.CFP_Franc_XPF: "XPF",
  CurrencyIso.Jamaican_Dollar_JMD: "JMD",
  CurrencyIso.Burundian_Franc_BIF: "BIF",
  CurrencyIso.Gibraltar_Pound_GIP: "GIP",
  CurrencyIso.Namibian_Dollar_NAD: "NAD",
  CurrencyIso.Syrian_Pound_SYP: "SYP",
  CurrencyIso.Surinamese_Dollar_SRD: "SRD",
  CurrencyIso.CFA_Franc_BEAC_XAF: "XAF",
  CurrencyIso.North_Korean_Won_KPW: "KPW",
  CurrencyIso.Norwegian_Krone_NOK: "NOK",
  CurrencyIso.Singapore_Dollar_SGD: "SGD",
  CurrencyIso.Bhutanese_Ngultrum_BTN: "BTN",
  CurrencyIso.Chinese_Yuan_CNY: "CNY",
  CurrencyIso.Malaysian_Ringgit_MYR: "MYR",
  CurrencyIso.Afghan_Afghani_AFN: "AFN",
  CurrencyIso.BosniaHerzegovinaConvertibleMarkBAM:
      "BosniaHerzegovinaConvertibleMarkBAM",
  CurrencyIso.Danish_Krone_DKK: "DKK",
  CurrencyIso.South_Korean_Won_KRW: "KRW",
  CurrencyIso.Chilean_Peso_CLP: "CLP",
  CurrencyIso.Guatemalan_Quetzal_GTQ: "GTQ",
  CurrencyIso.Serbian_Dinar_RSD: "RSD",
  CurrencyIso.Turkmenistani_Manat_TMT: "TMT",
  CurrencyIso.Armenian_Dram_AMD: "AMD",
  CurrencyIso.MauritanianOuguiyaMRO: "MauritanianOuguiyaMRO",
  CurrencyIso.Solomon_Islands_Dollar_SBD: "SBD",
  CurrencyIso.Belarusian_Ruble_BYN: "BYN",
  CurrencyIso.Bangladeshi_Taka_BDT: "BDT",
  CurrencyIso.Malawian_Kwacha_MWK: "MWK",
  CurrencyIso.Pakistani_Rupee_PKR: "PKR",
  CurrencyIso.South_African_Rand_ZAR: "ZAR",
  CurrencyIso.Zimbabwean_Dollar_ZWL: "ZWL",
  CurrencyIso.Bolivian_Boliviano_BOB: "BOB",
  CurrencyIso.Gold_Ounce_XAU: "XAU",
  CurrencyIso.Trinidad_and_Tobago_Dollar_TTD: "TTD",
  CurrencyIso.Peruvian_Nuevo_Sol_PEN: "PEN",
  CurrencyIso.Australian_Dollar_AUD: "AUD",
  CurrencyIso.Sri_Lankan_Rupee_LKR: "LKR",
  CurrencyIso.Sierra_Leonean_Leone_SLL: "SLL",
  CurrencyIso.Israeli_New_Sheqel_ILS: "ILS",
  CurrencyIso.Bitcoin_BTC: "BTC",
  CurrencyIso.Lebanese_Pound_LBP: "LBP",
  CurrencyIso.Rwandan_Franc_RWF: "RWF",
  CurrencyIso.Croatian_Kuna_HRK: "HRK",
  CurrencyIso.Honduran_Lempira_HNL: "HNL",
  CurrencyIso.Bermudan_Dollar_BMD: "BMD",
  CurrencyIso.Venezuelan_Bolivar_Fuerte_Old_VEF: "VEF",
  CurrencyIso.Congolese_Franc_CDF: "CDF",
  CurrencyIso.Guinean_Franc_GNF: "GNF",
  CurrencyIso.Indian_Rupee_INR: "INR",
  CurrencyIso.British_Pound_Sterling_GBP: "GBP",
  CurrencyIso.Samoan_Tala_WST: "WST",
  CurrencyIso.Netherlands_Antillean_Guilder_ANG: "ANG",
  CurrencyIso.Manx_pound_IMP: "IMP",
  CurrencyIso.Nicaraguan_Cordoba_NIO: "NIO",
  CurrencyIso.Algerian_Dinar_DZD: "DZD",
  CurrencyIso.South_Sudanese_Pound_SSP: "SSP",
  CurrencyIso.Swiss_Franc_CHF: "CHF",
  CurrencyIso.Bulgarian_Lev_BGN: "BGN",
  CurrencyIso.Egyptian_Pound_EGP: "EGP",
  CurrencyIso.Cayman_Islands_Dollar_KYD: "KYD",
  CurrencyIso.Mauritanian_Ouguiya_MRU: "MRU",
  CurrencyIso.Japanese_Yen_JPY: "JPY",
  CurrencyIso.Philippine_Peso_PHP: "PHP",
  CurrencyIso.Paraguayan_Guarani_PYG: "PYG",
  CurrencyIso.Swedish_Krona_SEK: "SEK",
  CurrencyIso.Cuban_Peso_CUP: "CUP",
  CurrencyIso.Hong_Kong_Dollar_HKD: "HKD",
  CurrencyIso.Iraqi_Dinar_IQD: "IQD",
  CurrencyIso.Dominican_Peso_DOP: "DOP",
  CurrencyIso.Kazakhstani_Tenge_KZT: "KZT",
  CurrencyIso.Hungarian_Forint_HUF: "HUF",
  CurrencyIso.Nigerian_Naira_NGN: "NGN",
  CurrencyIso.New_Taiwan_Dollar_TWD: "TWD",
  CurrencyIso.Nepalese_Rupee_NPR: "NPR",
  CurrencyIso.Ugandan_Shilling_UGX: "UGX",
  CurrencyIso.Silver_Ounce_XAG: "XAG",
  CurrencyIso.Angolan_Kwanza_AOA: "AOA",
  CurrencyIso.Comorian_Franc_KMF: "KMF",
  CurrencyIso.Myanma_Kyat_MMK: "MMK",
  CurrencyIso.CFA_Franc_BCEAO_XOF: "XOF",
  CurrencyIso.Georgian_Lari_GEL: "GEL",
  CurrencyIso.Gambian_Dalasi_GMD: "GMD",
  CurrencyIso.Seychellois_Rupee_SCR: "SCR",
  CurrencyIso.Tunisian_Dinar_TND: "TND",
  CurrencyIso.Cambodian_Riel_KHR: "KHR",
  CurrencyIso.Chinese_Yuan_Offshore_CNH: "CNH",
  CurrencyIso.Argentine_Peso_ARS: "ARS",
  CurrencyIso.Tajikistani_Somoni_TJS: "TJS",
  CurrencyIso.Russian_Ruble_RUB: "RUB",
  CurrencyIso.Ghanaian_Cedi_GHS: "GHS",
  CurrencyIso.Guyanaese_Dollar_GYD: "GYD",
  CurrencyIso.Djiboutian_Franc_DJF: "DJF",
  CurrencyIso.Mozambican_Metical_MZN: "MZN",
  CurrencyIso.Ukrainian_Hryvnia_UAH: "UAH",
  CurrencyIso.Bahamian_Dollar_BSD: "BSD",
  CurrencyIso.Aruban_Florin_AWG: "AWG",
  CurrencyIso.Vietnamese_Dong_VND: "VND",
  CurrencyIso.Icelandic_Krna_ISK: "ISK",
  CurrencyIso.Uzbekistan_Som_UZS: "UZS",
  CurrencyIso.Thai_Baht_THB: "THB",
  CurrencyIso.Uruguayan_Peso_UYU: "UYU",
  CurrencyIso.Macedonian_Denar_MKD: "MKD",
  CurrencyIso.Malagasy_Ariary_MGA: "MGA",
  CurrencyIso.Colombian_Peso_COP: "COP",
  CurrencyIso.Panamanian_Balboa_PAB: "PAB",
  CurrencyIso.Iranian_Rial_IRR: "IRR",
  CurrencyIso.TonganPangaTOP: "TonganPangaTOP",
  CurrencyIso.Albanian_Lek_ALL: "ALL",
};
