enum CurrencyIsoIos {
  Kuwait_KWD,
  SaudiArabia_SAR,
  Bahrain_BHD,
  UAE_AED,
  Qatar_QAR,
  Oman_MOR,
  Jordan_JOD,
  UnitedStates_USD,
  Euro_EUR,
  Cuban_Convertible_Peso_CUC,
  Falkland_Islands_Pound_FKP,
  Indonesian_Rupiah_IDR,
  Brazilian_Real_BRL,
  Costa_Rican_Colon_CRC,
  Maldivian_Rufiyaa_MVR,
  Brunei_Dollar_BND,
  Romanian_Leu_RON,
  Yemeni_Rial_YER,
  Lesotho_Loti_LSL,
  Mongolian_Tugrik_MNT,
  Papua_New_Guinean_Kina_PGK,
  Liberian_Dollar_LRD,
  Venezuelan_Bolivar_Soberano_VES,
  Cape_Verdean_Escudo_CVE,
  Palladium_Ounce_XPD,
  Haitian_Gourde_HTG,
  Saint_Helena_Pound_SHP,
  Kenyan_Shilling_KES,
  Moldovan_Leu_MDL,
  Kyrgystani_Som_KGS,
  New_Zealand_Dollar_NZD,
  Jersey_Pound_JEP,
  Macanese_Pataca_MOP,
  Moroccan_Dirham_MAD,
  Ethiopian_Birr_ETB,
  Turkish_Lira_TRY,
  Zambian_Kwacha_ZMW,
  East_Caribbean_Dollar_XCD,
  Libyan_Dinar_LYD,
  Sudanese_Pound_SDG,
  Tanzanian_Shilling_TZS,
  Vanuatu_Vatu_VUV,
  Platinum_Ounce_XPT,
  Fijian_Dollar_FJD,
  SaoTomAndPrincipeDobraSTD,
  Polish_Zloty_PLN,
  Canadian_Dollar_CAD,
  Guernsey_Pound_GGP,
  Chilean_Unit_of_Account_UF_CLF,
  Eritrean_Nakfa_ERN,
  Somali_Shilling_SOS,
  Botswanan_Pula_BWP,
  Belize_Dollar_BZD,
  Salvadoran_Colon_SVC,
  Sao_Tome_and_Principe_Dobra_STN,
  Azerbaijani_Manat_AZN,
  Barbadian_Dollar_BBD,
  Mauritian_Rupee_MUR,
  Special_Drawing_Rights_XDR,
  Laotian_Kip_LAK,
  Swazi_Lilangeni_SZL,
  Czech_Republic_Koruna_CZK,
  Mexican_Peso_MXN,
  CFP_Franc_XPF,
  Jamaican_Dollar_JMD,
  Burundian_Franc_BIF,
  Gibraltar_Pound_GIP,
  Namibian_Dollar_NAD,
  Syrian_Pound_SYP,
  Surinamese_Dollar_SRD,
  CFA_Franc_BEAC_XAF,
  North_Korean_Won_KPW,
  Norwegian_Krone_NOK,
  Singapore_Dollar_SGD,
  Bhutanese_Ngultrum_BTN,
  Chinese_Yuan_CNY,
  Malaysian_Ringgit_MYR,
  Afghan_Afghani_AFN,
  BosniaHerzegovinaConvertibleMarkBAM,
  Danish_Krone_DKK,
  South_Korean_Won_KRW,
  Chilean_Peso_CLP,
  Guatemalan_Quetzal_GTQ,
  Serbian_Dinar_RSD,
  Turkmenistani_Manat_TMT,
  Armenian_Dram_AMD,
  MauritanianOuguiyaMRO,
  Solomon_Islands_Dollar_SBD,
  Belarusian_Ruble_BYN,
  Bangladeshi_Taka_BDT,
  Malawian_Kwacha_MWK,
  Pakistani_Rupee_PKR,
  South_African_Rand_ZAR,
  Zimbabwean_Dollar_ZWL,
  Bolivian_Boliviano_BOB,
  Gold_Ounce_XAU,
  Trinidad_and_Tobago_Dollar_TTD,
  Peruvian_Nuevo_Sol_PEN,
  Australian_Dollar_AUD,
  Sri_Lankan_Rupee_LKR,
  Sierra_Leonean_Leone_SLL,
  Israeli_New_Sheqel_ILS,
  Bitcoin_BTC,
  Lebanese_Pound_LBP,
  Rwandan_Franc_RWF,
  Croatian_Kuna_HRK,
  Honduran_Lempira_HNL,
  Bermudan_Dollar_BMD,
  Venezuelan_Bolivar_Fuerte_Old_VEF,
  Congolese_Franc_CDF,
  Guinean_Franc_GNF,
  Indian_Rupee_INR,
  British_Pound_Sterling_GBP,
  Samoan_Tala_WST,
  Netherlands_Antillean_Guilder_ANG,
  Manx_pound_IMP,
  Nicaraguan_Cordoba_NIO,
  Algerian_Dinar_DZD,
  South_Sudanese_Pound_SSP,
  Swiss_Franc_CHF,
  Bulgarian_Lev_BGN,
  Egyptian_Pound_EGP,
  Cayman_Islands_Dollar_KYD,
  Mauritanian_Ouguiya_MRU,
  Japanese_Yen_JPY,
  Philippine_Peso_PHP,
  Paraguayan_Guarani_PYG,
  Swedish_Krona_SEK,
  Cuban_Peso_CUP,
  Hong_Kong_Dollar_HKD,
  Iraqi_Dinar_IQD,
  Dominican_Peso_DOP,
  Kazakhstani_Tenge_KZT,
  Hungarian_Forint_HUF,
  Nigerian_Naira_NGN,
  New_Taiwan_Dollar_TWD,
  Nepalese_Rupee_NPR,
  Ugandan_Shilling_UGX,
  Silver_Ounce_XAG,
  Angolan_Kwanza_AOA,
  Comorian_Franc_KMF,
  Myanma_Kyat_MMK,
  CFA_Franc_BCEAO_XOF,
  Georgian_Lari_GEL,
  Gambian_Dalasi_GMD,
  Seychellois_Rupee_SCR,
  Tunisian_Dinar_TND,
  Cambodian_Riel_KHR,
  Chinese_Yuan_Offshore_CNH,
  Argentine_Peso_ARS,
  Tajikistani_Somoni_TJS,
  Russian_Ruble_RUB,
  Ghanaian_Cedi_GHS,
  Guyanaese_Dollar_GYD,
  Djiboutian_Franc_DJF,
  Mozambican_Metical_MZN,
  Ukrainian_Hryvnia_UAH,
  Bahamian_Dollar_BSD,
  Aruban_Florin_AWG,
  Vietnamese_Dong_VND,
  Icelandic_Krna_ISK,
  Uzbekistan_Som_UZS,
  Thai_Baht_THB,
  Uruguayan_Peso_UYU,
  Macedonian_Denar_MKD,
  Malagasy_Ariary_MGA,
  Colombian_Peso_COP,
  Panamanian_Balboa_PAB,
  Iranian_Rial_IRR,
  TonganPangaTOP,
  Albanian_Lek_ALL
}

Map<CurrencyIsoIos, String> iosCurrencies = {
  CurrencyIsoIos.Kuwait_KWD: "KWD",
  CurrencyIsoIos.SaudiArabia_SAR: "SAR",
  CurrencyIsoIos.Bahrain_BHD: "BHD",
  CurrencyIsoIos.UAE_AED: "AED",
  CurrencyIsoIos.Qatar_QAR: "QAR",
  CurrencyIsoIos.Oman_MOR: "MOR",
  CurrencyIsoIos.Jordan_JOD: "JOD",
  CurrencyIsoIos.UnitedStates_USD: "USD",
  CurrencyIsoIos.Euro_EUR: "EUR",
  CurrencyIsoIos.Cuban_Convertible_Peso_CUC: "CUC",
  CurrencyIsoIos.Falkland_Islands_Pound_FKP: "FKP",
  CurrencyIsoIos.Indonesian_Rupiah_IDR: "IDR",
  CurrencyIsoIos.Brazilian_Real_BRL: "BRL",
  CurrencyIsoIos.Costa_Rican_Colon_CRC: "CRC",
  CurrencyIsoIos.Maldivian_Rufiyaa_MVR: "MVR",
  CurrencyIsoIos.Brunei_Dollar_BND: "BND",
  CurrencyIsoIos.Romanian_Leu_RON: "RON",
  CurrencyIsoIos.Yemeni_Rial_YER: "YER",
  CurrencyIsoIos.Lesotho_Loti_LSL: "LSL",
  CurrencyIsoIos.Mongolian_Tugrik_MNT: "MNT",
  CurrencyIsoIos.Papua_New_Guinean_Kina_PGK: "PGK",
  CurrencyIsoIos.Liberian_Dollar_LRD: "LRD",
  CurrencyIsoIos.Venezuelan_Bolivar_Soberano_VES:
      "VES",
  CurrencyIsoIos.Cape_Verdean_Escudo_CVE: "CVE",
  CurrencyIsoIos.Palladium_Ounce_XPD: "XPD",
  CurrencyIsoIos.Haitian_Gourde_HTG: "HTG",
  CurrencyIsoIos.Saint_Helena_Pound_SHP: "SHP",
  CurrencyIsoIos.Kenyan_Shilling_KES: "KES",
  CurrencyIsoIos.Moldovan_Leu_MDL: "MDL",
  CurrencyIsoIos.Kyrgystani_Som_KGS: "KGS",
  CurrencyIsoIos.New_Zealand_Dollar_NZD: "NZD",
  CurrencyIsoIos.Jersey_Pound_JEP: "JEP",
  CurrencyIsoIos.Macanese_Pataca_MOP: "MOP",
  CurrencyIsoIos.Moroccan_Dirham_MAD: "MAD",
  CurrencyIsoIos.Ethiopian_Birr_ETB: "ETB",
  CurrencyIsoIos.Turkish_Lira_TRY: "TRY",
  CurrencyIsoIos.Zambian_Kwacha_ZMW: "ZMW",
  CurrencyIsoIos.East_Caribbean_Dollar_XCD: "XCD",
  CurrencyIsoIos.Libyan_Dinar_LYD: "LYD",
  CurrencyIsoIos.Sudanese_Pound_SDG: "SDG",
  CurrencyIsoIos.Tanzanian_Shilling_TZS: "TZS",
  CurrencyIsoIos.Vanuatu_Vatu_VUV: "VUV",
  CurrencyIsoIos.Platinum_Ounce_XPT: "XPT",
  CurrencyIsoIos.Fijian_Dollar_FJD: "FJD",
  CurrencyIsoIos.SaoTomAndPrincipeDobraSTD: "SaoTomAndPrincipeDobraSTD",
  CurrencyIsoIos.Polish_Zloty_PLN: "PLN",
  CurrencyIsoIos.Canadian_Dollar_CAD: "CAD",
  CurrencyIsoIos.Guernsey_Pound_GGP: "GGP",
  CurrencyIsoIos.Chilean_Unit_of_Account_UF_CLF:
      "CLF",
  CurrencyIsoIos.Eritrean_Nakfa_ERN: "ERN",
  CurrencyIsoIos.Somali_Shilling_SOS: "SOS",
  CurrencyIsoIos.Botswanan_Pula_BWP: "BWP",
  CurrencyIsoIos.Belize_Dollar_BZD: "BZD",
  CurrencyIsoIos.Salvadoran_Colon_SVC: "SVC",
  CurrencyIsoIos.Sao_Tome_and_Principe_Dobra_STN:
      "STN",
  CurrencyIsoIos.Azerbaijani_Manat_AZN: "AZN",
  CurrencyIsoIos.Barbadian_Dollar_BBD: "BBD",
  CurrencyIsoIos.Mauritian_Rupee_MUR: "MUR",
  CurrencyIsoIos.Special_Drawing_Rights_XDR: "XDR",
  CurrencyIsoIos.Laotian_Kip_LAK: "LAK",
  CurrencyIsoIos.Swazi_Lilangeni_SZL: "SZL",
  CurrencyIsoIos.Czech_Republic_Koruna_CZK: "CZK",
  CurrencyIsoIos.Mexican_Peso_MXN: "MXN",
  CurrencyIsoIos.CFP_Franc_XPF: "XPF",
  CurrencyIsoIos.Jamaican_Dollar_JMD: "JMD",
  CurrencyIsoIos.Burundian_Franc_BIF: "BIF",
  CurrencyIsoIos.Gibraltar_Pound_GIP: "GIP",
  CurrencyIsoIos.Namibian_Dollar_NAD: "NAD",
  CurrencyIsoIos.Syrian_Pound_SYP: "SYP",
  CurrencyIsoIos.Surinamese_Dollar_SRD: "SRD",
  CurrencyIsoIos.CFA_Franc_BEAC_XAF: "XAF",
  CurrencyIsoIos.North_Korean_Won_KPW: "KPW",
  CurrencyIsoIos.Norwegian_Krone_NOK: "NOK",
  CurrencyIsoIos.Singapore_Dollar_SGD: "SGD",
  CurrencyIsoIos.Bhutanese_Ngultrum_BTN: "BTN",
  CurrencyIsoIos.Chinese_Yuan_CNY: "CNY",
  CurrencyIsoIos.Malaysian_Ringgit_MYR: "MYR",
  CurrencyIsoIos.Afghan_Afghani_AFN: "AFN",
  CurrencyIsoIos.BosniaHerzegovinaConvertibleMarkBAM:
      "BosniaHerzegovinaConvertibleMarkBAM",
  CurrencyIsoIos.Danish_Krone_DKK: "DKK",
  CurrencyIsoIos.South_Korean_Won_KRW: "KRW",
  CurrencyIsoIos.Chilean_Peso_CLP: "CLP",
  CurrencyIsoIos.Guatemalan_Quetzal_GTQ: "GTQ",
  CurrencyIsoIos.Serbian_Dinar_RSD: "RSD",
  CurrencyIsoIos.Turkmenistani_Manat_TMT: "TMT",
  CurrencyIsoIos.Armenian_Dram_AMD: "AMD",
  CurrencyIsoIos.MauritanianOuguiyaMRO: "MauritanianOuguiyaMRO",
  CurrencyIsoIos.Solomon_Islands_Dollar_SBD: "SBD",
  CurrencyIsoIos.Belarusian_Ruble_BYN: "BYN",
  CurrencyIsoIos.Bangladeshi_Taka_BDT: "BDT",
  CurrencyIsoIos.Malawian_Kwacha_MWK: "MWK",
  CurrencyIsoIos.Pakistani_Rupee_PKR: "PKR",
  CurrencyIsoIos.South_African_Rand_ZAR: "ZAR",
  CurrencyIsoIos.Zimbabwean_Dollar_ZWL: "ZWL",
  CurrencyIsoIos.Bolivian_Boliviano_BOB: "BOB",
  CurrencyIsoIos.Gold_Ounce_XAU: "XAU",
  CurrencyIsoIos.Trinidad_and_Tobago_Dollar_TTD:
      "TTD",
  CurrencyIsoIos.Peruvian_Nuevo_Sol_PEN: "PEN",
  CurrencyIsoIos.Australian_Dollar_AUD: "AUD",
  CurrencyIsoIos.Sri_Lankan_Rupee_LKR: "LKR",
  CurrencyIsoIos.Sierra_Leonean_Leone_SLL: "SLL",
  CurrencyIsoIos.Israeli_New_Sheqel_ILS: "ILS",
  CurrencyIsoIos.Bitcoin_BTC: "BTC",
  CurrencyIsoIos.Lebanese_Pound_LBP: "LBP",
  CurrencyIsoIos.Rwandan_Franc_RWF: "RWF",
  CurrencyIsoIos.Croatian_Kuna_HRK: "HRK",
  CurrencyIsoIos.Honduran_Lempira_HNL: "HNL",
  CurrencyIsoIos.Bermudan_Dollar_BMD: "BMD",
  CurrencyIsoIos.Venezuelan_Bolivar_Fuerte_Old_VEF:
      "VEF",
  CurrencyIsoIos.Congolese_Franc_CDF: "CDF",
  CurrencyIsoIos.Guinean_Franc_GNF: "GNF",
  CurrencyIsoIos.Indian_Rupee_INR: "INR",
  CurrencyIsoIos.British_Pound_Sterling_GBP: "GBP",
  CurrencyIsoIos.Samoan_Tala_WST: "WST",
  CurrencyIsoIos.Netherlands_Antillean_Guilder_ANG:
      "ANG",
  CurrencyIsoIos.Manx_pound_IMP: "IMP",
  CurrencyIsoIos.Nicaraguan_Cordoba_NIO: "NIO",
  CurrencyIsoIos.Algerian_Dinar_DZD: "DZD",
  CurrencyIsoIos.South_Sudanese_Pound_SSP: "SSP",
  CurrencyIsoIos.Swiss_Franc_CHF: "CHF",
  CurrencyIsoIos.Bulgarian_Lev_BGN: "BGN",
  CurrencyIsoIos.Egyptian_Pound_EGP: "EGP",
  CurrencyIsoIos.Cayman_Islands_Dollar_KYD: "KYD",
  CurrencyIsoIos.Mauritanian_Ouguiya_MRU: "MRU",
  CurrencyIsoIos.Japanese_Yen_JPY: "JPY",
  CurrencyIsoIos.Philippine_Peso_PHP: "PHP",
  CurrencyIsoIos.Paraguayan_Guarani_PYG: "PYG",
  CurrencyIsoIos.Swedish_Krona_SEK: "SEK",
  CurrencyIsoIos.Cuban_Peso_CUP: "CUP",
  CurrencyIsoIos.Hong_Kong_Dollar_HKD: "HKD",
  CurrencyIsoIos.Iraqi_Dinar_IQD: "IQD",
  CurrencyIsoIos.Dominican_Peso_DOP: "DOP",
  CurrencyIsoIos.Kazakhstani_Tenge_KZT: "KZT",
  CurrencyIsoIos.Hungarian_Forint_HUF: "HUF",
  CurrencyIsoIos.Nigerian_Naira_NGN: "NGN",
  CurrencyIsoIos.New_Taiwan_Dollar_TWD: "TWD",
  CurrencyIsoIos.Nepalese_Rupee_NPR: "NPR",
  CurrencyIsoIos.Ugandan_Shilling_UGX: "UGX",
  CurrencyIsoIos.Silver_Ounce_XAG: "XAG",
  CurrencyIsoIos.Angolan_Kwanza_AOA: "AOA",
  CurrencyIsoIos.Comorian_Franc_KMF: "KMF",
  CurrencyIsoIos.Myanma_Kyat_MMK: "MMK",
  CurrencyIsoIos.CFA_Franc_BCEAO_XOF: "XOF",
  CurrencyIsoIos.Georgian_Lari_GEL: "GEL",
  CurrencyIsoIos.Gambian_Dalasi_GMD: "GMD",
  CurrencyIsoIos.Seychellois_Rupee_SCR: "SCR",
  CurrencyIsoIos.Tunisian_Dinar_TND: "TND",
  CurrencyIsoIos.Cambodian_Riel_KHR: "KHR",
  CurrencyIsoIos.Chinese_Yuan_Offshore_CNH: "CNH",
  CurrencyIsoIos.Argentine_Peso_ARS: "ARS",
  CurrencyIsoIos.Tajikistani_Somoni_TJS: "TJS",
  CurrencyIsoIos.Russian_Ruble_RUB: "RUB",
  CurrencyIsoIos.Ghanaian_Cedi_GHS: "GHS",
  CurrencyIsoIos.Guyanaese_Dollar_GYD: "GYD",
  CurrencyIsoIos.Djiboutian_Franc_DJF: "DJF",
  CurrencyIsoIos.Mozambican_Metical_MZN: "MZN",
  CurrencyIsoIos.Ukrainian_Hryvnia_UAH: "UAH",
  CurrencyIsoIos.Bahamian_Dollar_BSD: "BSD",
  CurrencyIsoIos.Aruban_Florin_AWG: "AWG",
  CurrencyIsoIos.Vietnamese_Dong_VND: "VND",
  CurrencyIsoIos.Icelandic_Krna_ISK: "ISK",
  CurrencyIsoIos.Uzbekistan_Som_UZS: "UZS",
  CurrencyIsoIos.Thai_Baht_THB: "THB",
  CurrencyIsoIos.Uruguayan_Peso_UYU: "UYU",
  CurrencyIsoIos.Macedonian_Denar_MKD: "MKD",
  CurrencyIsoIos.Malagasy_Ariary_MGA: "MGA",
  CurrencyIsoIos.Colombian_Peso_COP: "COP",
  CurrencyIsoIos.Panamanian_Balboa_PAB: "PAB",
  CurrencyIsoIos.Iranian_Rial_IRR: "IRR",
  CurrencyIsoIos.TonganPangaTOP: "TonganPangaTOP",
  CurrencyIsoIos.Albanian_Lek_ALL: "ALL",
};
